
# pubspec.yaml
name: flutter_persistent_state
description: Eliminate boilerplate for app-global persistent state management in Flutter. Automatic hydration, reactive updates, and seamless integration with navigation and text fields.
version: 1.0.0
homepage: https://github.com/samuelkchris/flutter_persistent_state
repository: https://github.com/samuelkchris/flutter_persistent_state
issue_tracker: https://github.com/samuelkchris/flutter_persistent_state/issues
documentation: https://samuelkchris.github.io/flutter_persistent_state/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  source_gen: ^1.4.0
  code_builder: ^4.7.0
  dart_style: ^2.3.2
  analyzer: ^6.2.0

  